---
title: "ფორმულები"
author: "დავით სიჭინავა"
output: html_document

---

### წინამდებარე ფორმულები პრეზენტაციებშიცაა, თუმცა აქ მაინც გამომაქვს:

#### როგორ ვიპოვოთ განაწილების მედიანა (სოციალურ მეცნიერებათა ლექსიკონი):

,,ადამიანის შემოსავალი არის $10200, 10400, 10700, _11200_, 11300, 11500 და 200000. თუ ამ რიცხვებს დავალაგებთ ზრდის მიხედვით, მედიანა, როგორც შუა რიცხვი იქნება 11200 (მონაცემთა რაოდენობა კენტია)."

,,თუ მონაცემთა რაოდენობა ლუწია, მაგალითად 70, 77, _77, 81_, 84 და 88 მედიანა არის შუა ორი მონაცემის საშუალო (77 +81)/2=79."

არ დაგავიწყდეთ რიცხვების ზრდის მიხედვით დალაგება!

[წყარო](http://dictionary.css.ge/content/median)

#### როგორ ვიპოვოთ განაწილების სტანდარტული გადახრა (სოციალურ მეცნიერებათა ლექსიკონი):

$s = \sqrt{\frac{\sum {(X_{i}-\overline{X})}^2}{n-1}}$

ვთქვათ, გვაქვს შემდეგი განაწილება: 1, 2, 3. სტანდარტული გადახრის საპოვნელად, უნდა მოიქცეთ შემდეგნაირად:

* გამოთვალოთ განაწილების არითმეტიკული საშუალო: $(1+2+3)/3$
* გამოთვალოთ საშუალოს და თითოეული რიცხვის სხვაობების კვადრატი:
	* ${(1-2)}^2 = 1$;
	+ ${(2-2)}^2 = 0$;
	+ ${(3-2)}^2 = 1$;
* გამოვთვალოთ მიღებული რიცხვების ჯამი
	+ $1 + 0 + 1 = 2$ (მრიცხველი);
* გაყავით მიღებული შედეგები ჩანაწერების რაოდენობას მინუს ერთზე
	+ $2-1 = 2$ (მნიშვნელი);
* გაყავით მრიცხველი (2) მნიშვნელზე (2) და ამოიღეთ კვადრატული ფესვი
	+ $\sqrt{\frac{2}{2}} = 1$
	
გაითვალისწინეთ, რომ გამოთვლა არ არის აუცილებელი. რიცხვების ჩასმაც საკმარისი იქნება.
	
[წყარო](http://dictionary.css.ge/content/mean-square-deviation-variance-adjusted-variance)


#### როგორ ვიპოვოთ პროპორციის შერჩევის ზომა:

$n =\dfrac{\hat{p}(1-\hat{p}) z^2}{ME^2}$, სადაც $\hat{p}$ წარმოადგენს პროპორციის საშუალოს. თუ მიახლოებითი წარმოდგენაც არ გვაქვს, თუ თეორიულად როგორ იქნება განაწილებული პასუხები პროპორციაში, ვიღებთ $0.5$-ს. $z^2$-ის მნიშვნელობისთვის, სტანდარტულად ვიღებთ $1.96$-ს, 95%-იანი ნდობის ინტერვალის გათვალისწინებით. რაც შეეხება $ME$-ს, იგი მიგვითითებს დასაშვებ ცდომილებაზე. მაგალითად, თუ ჩვენი გამოკითხვა ,,აიტანს'' 2.3%-იან ცდომილებას, მაშინ $ME$-ს მნიშვნელობად ავიღებთ $0.023$-ს.

წარმოიდგინეთ შემდეგი სიტუაცია: უნდა გამოვთვალოთ შერჩევის ზომა ისეთი გამოკითხვისთვის, რომლის მიხედვითაც უნდა გამოვიცნოთ, რას უჭერს თუ არა საქართველოს მოსახლეობა მხარს ევროკავშირში გაწევრიანებას, ცდომილება 95%-იანი სანდოობის ინტერვალით უნდა იყოს 4.1%. რადგან მიახლოებითაც არ ვიცით, თუ რას ფიქრობს საქართველოს მოსახლეობა ამ საკითხთან დაკავშირებით, პროპორციის მნიშვნელობად ავიღებთ $0.5$-ს. რადგან $95\%$-იან ნდობის ინტერვალთან გვაქვს საქმე, $z$-ის მნიშვნელობად ვიღებთ $1.96$-ს. ფორმულაში ეს ყველაფერი შემდეგნაირად გამოიყურება:

$n =\frac{0.5(1-0.5) 1.96^2}{0.041^2} \approx 571$

ანუ ასეთი კვლევისთვის დაახლოებით 571 რესპონდენტის გამოკითხვა დაგჭირდებათ.

გაითვალისწინეთ, რომ გამოთვლა არ არის აუცილებელი. ფორმულის სწავლა და რიცხვების ჩასმაც საკმარისი იქნება.
